# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lensed < Formula
  desc ""
  homepage "https://github.com/kubecfg/lensed"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubecfg/lensed/releases/download/v0.0.7/lensed_0.0.7_darwin_arm64.tar.gz"
      sha256 "f9fb3bd6d442666ac1d71de0fdc056666a6d5d742453ef1778633deb2b36dced"

      def install
        bin.install "lensed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubecfg/lensed/releases/download/v0.0.7/lensed_0.0.7_darwin_amd64.tar.gz"
      sha256 "f5d81a2c08597b8f2fe0ab64e0a7ef4c399a892e60728c3b17e00daddbdb660a"

      def install
        bin.install "lensed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubecfg/lensed/releases/download/v0.0.7/lensed_0.0.7_linux_amd64.tar.gz"
      sha256 "ee0003ff2c29bc4f0785746d2c90197db0b667f45280aefe5392067007788300"

      def install
        bin.install "lensed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubecfg/lensed/releases/download/v0.0.7/lensed_0.0.7_linux_arm64.tar.gz"
      sha256 "c65360debfb7be6c49f821963f151fd649f1cc67beef2d605e2e57f3e76b08ff"

      def install
        bin.install "lensed"
      end
    end
  end
end
