# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lensed < Formula
  desc ""
  homepage "https://github.com/kubecfg/lensed"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kubecfg/lensed/releases/download/v0.0.6/lensed_0.0.6_darwin_arm64.tar.gz"
      sha256 "e669d254c7e57dd44d4ce85f403b6fbb3dc7697daaf635eef460cd156112c340"

      def install
        bin.install "lensed"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubecfg/lensed/releases/download/v0.0.6/lensed_0.0.6_darwin_amd64.tar.gz"
      sha256 "dbe2ea52ae36109a59a56acd831e6276890a7ce20fd83e3bcba0e3b89f936ff8"

      def install
        bin.install "lensed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubecfg/lensed/releases/download/v0.0.6/lensed_0.0.6_linux_amd64.tar.gz"
      sha256 "5284596addb296422923f84bf3a549daeabb3ae498d6a8fc6a178783936981c8"

      def install
        bin.install "lensed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubecfg/lensed/releases/download/v0.0.6/lensed_0.0.6_linux_arm64.tar.gz"
      sha256 "3bc8238039828115409cf494550f9ab486f90f405b3081208db8e7756718d6f6"

      def install
        bin.install "lensed"
      end
    end
  end
end
